In [2]:
import numpy as np
arr=np.random.randn(4,3)
print('Array:')
print('---------------------------------------------------------------------------')
print(arr)
print()
print('Size of Array:')
print('---------------------------------------------------------------------------')
print(arr.size)
print()
print('Size of particular row (row 2):')
print('---------------------------------------------------------------------------')
print(len(arr[:,2]))
print()
print('Size of particular column (column 2):')
print('---------------------------------------------------------------------------')
print(len(arr[2,:]))
print()
print('Taking input from file: ')
print('---------------------------------------------------------------------------')
with open('numpy2text.txt', 'r') as f:
    l =np.loadtxt(f)
print(l)
print()
print('Saving Array to a file: ')
print('---------------------------------------------------------------------------')
with open('numpy2output.txt', 'wb') as f:
    np.savetxt(f,arr)

Array:
---------------------------------------------------------------------------
[[ 0.18034035 -1.8479705   0.90080596]
 [-0.41977762  0.57493183  1.69447267]
 [-1.19121192 -0.36369531  0.54476833]
 [ 0.28807596 -0.6950863  -0.89230916]]

Size of Array:
---------------------------------------------------------------------------
12

Size of particular row (row 2):
---------------------------------------------------------------------------
4

Size of particular column (column 2):
---------------------------------------------------------------------------
3

Taking input from file: 
---------------------------------------------------------------------------
[ 2.    -3.     4.     5.     2.111]

Saving Array to a file: 
---------------------------------------------------------------------------
