In [2]:
import numpy as np
mat1= np.random.randint(1,10,(3,3))
mat2= np.random.randint(1,10,(3,3))
print("Matrix 1:")
print(mat1)
print("Matrix 2:")
print(mat2)
print()
print('Addition of Two matrices')
print('---------------------------------------------------------------------------')
mat3=mat1+mat2
print(mat3)
print()
print('Subtraction of Two matrices')
print('---------------------------------------------------------------------------')
mat3=mat1+mat2
print(mat3)
print()
print('Multiplication of Two matrices')
print('---------------------------------------------------------------------------')
mat3=mat1*mat2
print(mat3)
print()

mat1= np.random.randint(1,10,(4,3))
mat2= np.random.randint(1,10,(3,2))
print("Matrix 1:")
print(mat1)
print("Matrix 2:")
print(mat2)
print()
print('Element-by-Element Multiplication of Two matrices')
print('---------------------------------------------------------------------------')
mat3=mat1.dot(mat2)
print(mat3)
print()
print('Displaying Specific Rows and column')
print('---------------------------------------------------------------------------')
print(mat3[1:,1:])

Matrix 1:
[[1 3 5]
 [4 6 6]
 [7 9 3]]
Matrix 2:
[[9 4 5]
 [4 3 5]
 [2 4 6]]

Addition of Two matrices
---------------------------------------------------------------------------
[[10  7 10]
 [ 8  9 11]
 [ 9 13  9]]

Subtraction of Two matrices
---------------------------------------------------------------------------
[[10  7 10]
 [ 8  9 11]
 [ 9 13  9]]

Multiplication of Two matrices
---------------------------------------------------------------------------
[[ 9 12 25]
 [16 18 30]
 [14 36 18]]

Matrix 1:
[[2 1 5]
 [9 3 7]
 [2 1 2]
 [7 7 9]]
Matrix 2:
[[7 1]
 [5 3]
 [9 7]]

Element-by-Element Multiplication of Two matrices
---------------------------------------------------------------------------
[[ 64  40]
 [141  67]
 [ 37  19]
 [165  91]]

Displaying Specific Rows and column
---------------------------------------------------------------------------
[[67]
 [19]
 [91]]
