In [1]:
import numpy as np

arr=np.random.randn(4,3)
print('Array:')
print('---------------------------------------------------------------------------')
print(arr)
print()
print('Absolute Value of the Array')
print('---------------------------------------------------------------------------')
print(np.absolute(arr))
print()
print('Negative Value of the Array')
print('---------------------------------------------------------------------------')
print(np.negative(arr))
print()
print('Array after deleting row 2')
print('---------------------------------------------------------------------------')
print(np.delete(arr,2,0))
print()
print('Array after deleting column 2')
print('---------------------------------------------------------------------------')
print(np.delete(arr,2,1))
print()
print('Maximum of Array')
print('---------------------------------------------------------------------------')
print(np.max(arr))
print()
print('Minimum of Array')
print('---------------------------------------------------------------------------')
print(np.min(arr))
print()
print('Sum of all elements of Array')
print('---------------------------------------------------------------------------')
print(np.sum(arr))
print()
print('Sum of all elements of Array row-wise')
print('---------------------------------------------------------------------------')
print(np.sum(arr,0))
print()
print('Sum of all elements of Array column-wise')
print('---------------------------------------------------------------------------')
print(np.sum(arr,1))

Array:
---------------------------------------------------------------------------
[[-1.10090996 -0.05798599 -0.49674425]
 [-0.61077552  0.68824105  1.22638078]
 [-0.28480265  0.89756575 -0.9547192 ]
 [ 0.6482356   1.30705694  0.29673199]]

Absolute Value of the Array
---------------------------------------------------------------------------
[[1.10090996 0.05798599 0.49674425]
 [0.61077552 0.68824105 1.22638078]
 [0.28480265 0.89756575 0.9547192 ]
 [0.6482356  1.30705694 0.29673199]]

Negative Value of the Array
---------------------------------------------------------------------------
[[ 1.10090996  0.05798599  0.49674425]
 [ 0.61077552 -0.68824105 -1.22638078]
 [ 0.28480265 -0.89756575  0.9547192 ]
 [-0.6482356  -1.30705694 -0.29673199]]

Array after deleting row 2
---------------------------------------------------------------------------
[[-1.10090996 -0.05798599 -0.49674425]
 [-0.61077552  0.68824105  1.22638078]
 [ 0.6482356   1.30705694  0.29673199]]

Array after deleting colu